### ISSUE TITLE
Syntax error when running

### ISSUE THREAD

**Issue by jcmcnch** [WeiliWw/VirHostMatcher-Net#1]
Hi Weli,

When running:

`VirHostMatcher-Net.py -q ./split -t 2 --short-contig -o 180305_VirHostMatcher-Net_output -n 5`

I get the following errors:

```
/home/jesse/build/VirHostMatcher-Net/VirHostMatcher-Net.py: line 3: $'\nMain function\n': command not found
/home/jesse/build/VirHostMatcher-Net/VirHostMatcher-Net.py: line 8: syntax error near unexpected token `('
/home/jesse/build/VirHostMatcher-Net/VirHostMatcher-Net.py: line 8: `parser = argparse.ArgumentParser(description='VirHostMatcher-Net: A network-based tool for predicting hosts given query viruses')'

```

Any help to resolve this would be appreciated.

Jesse McNichol
Fuhrman lab

**Comment by WeiliWw** [comment]
Hi Jesse,

The easiest way to fix the issue is to add `python` before the command:

`python VirHostMatcher-Net.py -q ./split -t 2 --short-contig -o 180305_VirHostMatcher-Net_output -n 5`

Alternatively, I just added a shebang line to `VirHostMatcher-Net.py`. Now once it is made executable, it knows to call the python interpreter.

Best,
Weili

**Comment by jcmcnch** [comment]
If I put python before the command I can only run it by providing the absolute path. Even when I do that, I get an error:

```
python ~/build/VirHostMatcher-Net/VirHostMatcher-Net.py -q ./split -t 2 --short-contig -o 180305_VirHostMatcher-Net_output -n 5
  File "/home/jesse/build/VirHostMatcher-Net/VirHostMatcher-Net.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

I get a similar error running it without python at the beginning:

```
VirHostMatcher-Net.py -q ./split -t 2 --short-contig -o 180305_VirHostMatcher-Net_output -n 5
/home/jesse/build/VirHostMatcher-Net/VirHostMatcher-Net.py: line 7: syntax error near unexpected token `newline'
/home/jesse/build/VirHostMatcher-Net/VirHostMatcher-Net.py: line 7: `<!DOCTYPE html>'
```
