### ISSUE TITLE
Bacterial MAGs

### ISSUE THREAD

**Issue by drob2727** [WeiliWw/VirHostMatcher-Net#11]
I have my own bacterial genomes assembled from my samples that potentially are not in the NCBI database. Is there a way to use the metagenomic assembled genomes from my own samples?

**Comment by Thexiyang** [comment]
Same question here.

**Comment by WeiliWw** [comment]
There is no easy way to integrate them into the software, but you can manually calculate the prediction scores between the assembled genomes and virus/phage of interest - following Equation 6 from the paper.  The parameters are provided [here](https://github.com/WeiliWw/VirHostMatcher-Net/blob/master/src/Variables.py#L12-L13). (Particularly for the term SV+, I assume the value would be zero as there might be no known virus/phage for that bacteria.)

Once you have the prediction scores, compare them to the predictions for existing bacterial genomes in the software. But you might want to take a grain of salt on strain-level predictions. Our tool would have higher accuracy on broader taxonomic level predictions, and that is feasible by using annotated bacteria with known taxonomy info.
