### ISSUE TITLE
Training on new phage-host pairs

### ISSUE THREAD

**Issue by KennthShang** [WeiliWw/VirHostMatcher-Net#12]
Hi. I have a problem when I want to use the VHM-Net.

Seems the model can only be used to make predictions but not be re-train? I am not sure whether it is possible to add new training samples.

Also, is there a possible way to download the dataset used for VHM-Net? Seems there is not a link or accessions in the paper.

Thanks!

**Comment by WeiliWw** [comment]
Yes, we do provide the training dataset at http://www-rcf.usc.edu/~weiliw/VirHostMatcher-Net/.  You can combine it with your own samples to train a new model.

**Comment by KennthShang** [comment]
Sorry, I did not make it clear. The first question is: is there a guideline or script to re-train the model?
