### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by bishav6708** [WeiliWw/VirHostMatcher-Net#18]
Hello, I get the following error while running VirHostMatcher-Net.py.

I checked this issue has been reported before but the solution to that didn't solve my problem.

This is the command I used:

python3 VirHostMatcher-Net.py -q /mnt/nas/vol1/splitted_viruses_6/ -o /mnt/nas/vol1/VHM_try1 -t 8 -d ./data

Traceback (most recent call last):
  File "VirHostMatcher-Net.py", line 56, in <module>
    predictor = HostPredictor(query_virus_dir, args.short_contig, intermediate_dir, genome_list, args.num_Threads)
  File "/mnt/nas/vol1/softwares/VirHostMatcher-Net/predictor.py", line 47, in __init__
    self._crispr_signals = src.crispr.crispr_calculator(query_virus_dir, intermediate_dir, numThreads)
  File "/mnt/nas/vol1/softwares/VirHostMatcher-Net/src/crispr.py", line 82, in crispr_calculator
    ind, df = crisprSingle(item, query_virus_dir, crispr_output_dir, numThreads)
  File "/mnt/nas/vol1/softwares/VirHostMatcher-Net/src/crispr.py", line 43, in crisprSingle
    crispr_call()
  File "/usr/local/lib64/python3.6/site-packages/Bio/Application/__init__.py", line 527, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'blastn -out /mnt/nas/vol1/softwares/VirHostMatcher-Net/intermediate_res/CRISPR/viruses_6_0.crispr -outfmt 6 qacc sacc evalue -query /mnt/nas/vol1/splitted_viruses_6/viruses_6_0.fa -db ./data/crispr_db_prefix/allCRISPRs -evalue 1 -word_size 7 -num_threads 8 -gapopen 10 -gapextend 2 -task blastn-short -penalty -1 -dust no -perc_identity 90', message 'USAGE'

**Comment by WeiliWw** [comment]
Hi, this is a known issue with the Biopython version. Could you try to update your biopython module or add single quotation marks back at line 40 in src/crispr.py (revert [this change](https://github.com/WeiliWw/VirHostMatcher-Net/commit/1f10bd160d4a014bdf4c8aeebb657c285a3ca507) on the file).
