### ISSUE TITLE
Run the analysis having already calculated the CRISPR values

### ISSUE THREAD

**Issue by miczuppi** [WeiliWw/VirHostMatcher-Net#19]
Hi,
I am running VirHostMatcher-Net on multiple fasta files.
After having calculated for each of them the CRISPR values, my analysis was interrupted.
I was wondering if there is a way to proceed with the analysis using the CRISPR values that I have , without having to calculate them again.

Thank you for your time,
Michele

**Comment by WeiliWw** [comment]
Hi Michele,

Yes, the CRISPR results are stored in the intermediate directory - what you specified by `-i` in the command (default `./intermediate_res`). The CRISPR results for each query fasta are in a separate file with the original fasta file's name.

**Comment by miczuppi** [comment]
Hi, 
Thank you for the quick reply. 
So I can run VirHostMatcher-Net again using the CRISPR results as input?

Thank you for your time,
Michele

**Comment by WeiliWw** [comment]
I thought you wanted to grab the results for your own analysis.

If you just want to run VirHostMatcher-Net again and skip the CRIPSR calculation, you can first comment out lines 40-42 in /src/crispr.py (the lines with `crispr_call = NcbiblastnCommandline(...)`) and then re-run the same command you used before.

**Comment by miczuppi** [comment]
Ok, thank you very much.

Michele
