### ISSUE TITLE
kmer_count from src.tools error

### ISSUE THREAD

**Issue by CynthiaChibani** [WeiliWw/VirHostMatcher-Net#2]
Hey there,
i am trying to run virhostmatcher-net and i get this error:
from .tools import kmer_count
ImportError: cannot import name 'kmer_count' from 'src.tools' (unknown location)

i downloaded the tool from source and when i go to ./src/tools/ i find kmer_count_multithreads.h

**Comment by WeiliWw** [comment]
Hello, 

Have you built the local dependent modules? If not, please refer to the section `Building local dependent modules` in README.
