### ISSUE TITLE
Running VirHostMatcher-Net with a personal genome list

### ISSUE THREAD

**Issue by miczuppi** [WeiliWw/VirHostMatcher-Net#22]
Hi, 
I have sequenced both the bacteriome and the phageome of my samples, and I would like to assess which bacteria in the sample is infected by which phage. 
I was then thinking to use VirHostMatcher-Net on my phages using, for the `-l GENOME_LIST` flag, a personal genome list created from my bacteriome.
Would that be possible?

Thank you for your time.

Michele Zuppi

**Comment by WeiliWw** [comment]
Hi Michele,

Unfortunately the tool does not support adding new bacterial genomes. You will need to prepare the following data:
-  s2star between new bacterial genomes and the training set
-  BLAST and CRISPR matches between the new bacterial genomes and the phageome of interest

And then calculate the score with the formula and parameters.

Best,
Weili
