### ISSUE TITLE
short-contig   mode

### ISSUE THREAD

**Issue by lingyi-owl** [WeiliWw/VirHostMatcher-Net#24]
Hi Developer,

I want to use the --short-contig  mode  to predict hosts for short viral contigs but I am not sure what the criteria of short contigs are in your program. Is it based on a length cutoff? I am looking forward to your reply.

Best,
Lingyi

**Comment by WeiliWw** [comment]
Hi Lingyi, My apologies for such a late reply! Generally you may consider using the short contig mode for contigs under 20k. For longer ones it's up to how complete you think the assembled sequences are.
