### ISSUE TITLE
hostTaxa.pkl not found

### ISSUE THREAD

**Issue by CynthiaChibani** [WeiliWw/VirHostMatcher-Net#3]
I came across another error:
FileNotFoundError: [Errno 2] No such file or directory: ~/VirHostMatcher-Net/data/tables/hostTaxa.pkl

**Comment by WeiliWw** [comment]
Hello, Thanks for your interest! We've just updated the entire dataset. Please re-download the data from `http://www-rcf.usc.edu/~weiliw/VirHostMatcher-Net/`.
