### ISSUE TITLE
ImportError: No module named tools

### ISSUE THREAD

**Issue by sunettevos** [WeiliWw/VirHostMatcher-Net#5]
Good day

I am also using this tool to predict virus-host interactions. I am however running in the following issues. The command I am using
 $ python VirHostMatcher-Net.py -q virus-fasta/ --short-contig -o output/ -n 3 -t 8.

The error I am getting:
 File "VirHostMatcher-Net/VirHostMatcher-Net.py", line 44, in <module>
    from predictor import HostPredictor
  File "/home/sunette/VirHostMatcher-Net/predictor.py", line 4, in <module>
    import src.s2star
  File "/home/sunette/VirHostMatcher-Net/src/s2star.py", line 9, in <module>
    from .tools import kmer_count
ImportError: No module named tools

I am running this from inside the VirusHostMatcher directory. I get the same problem when running outside this directory specifying the path to the tool. We did install the dependent modules, I can see the src directory with the src.s2star files in there. Not sure what is causing this error message. Did the dependent tools fail to install properly or why am I getting this error message? As mentioned we have installed the tool using the Github repository where we have followed the instructions on the READme file. Any help on this will be appreciated, seems like a very nice tool to use from the paper I have read. 

Regards
Sunette

**Comment by WeiliWw** [comment]
Hi Sunette, 

Could you post the output when you built the local dependent modules? Should be the output of one of these two commands:
`CC=g++ python setup.py install --install-platlib=./src/`
or
`MACOSX_DEPLOYMENT_TARGET=10.9 CC=g++ python setup.py install --install-platlib=./src/`

**Comment by sunettevos** [comment]
Good day

Seems like we have an outdated version of the g++ in our server. I have managed to install the tool in the Linux terminal on my own laptop, however it seems like the host_wish_model from the data files (wget -c http://www-rcf.usc.edu/~weiliw/VirHostMatcher-Net/data_VirHostMatcher-Net_complete_genome_mode_alone.tar.gz and wget -c http://www-rcf.usc.edu/~weiliw/VirHostMatcher-Net/data_VirHostMatcher-Net_both_modes.tar.gz) is broken somehow. After extracting the tar xf data_VirHostMatcher-Net_complete_genome_mode_alone.tar.gz, the host_wish_model link remains red, not sure why this is the case. After doing tar xf data_VirHostMatcher-Net_both_modes.tar.gz, for some reason I get the following error: 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Will you please be able to assist me with this problem. 

Regards
Sunette

**Comment by WeiliWw** [comment]
Hi Sunette,

It seems good for both downloading and decompressing from our side, and we haven't heard a similar issue from other users... Could you try to download it again? Thanks!

Best,
Weili
