### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by ClovisG** [WeiliWw/VirHostMatcher-Net#6]
Hi there,
Thanks for the interesting tool. I cannot find in your code a belief propagation part for the MRF inference. If my understanding of your code is correct, it looks like the network in static (i.e. does not depend on the predicted data). Am I right?
To complete my understanding I have the following questions:
 - How did you infer the regression coefficients?
 - How did you infer the network ? Did you use belief propagation?
 - Is it possible to retrain your model with newly available data?

Thanks a lot!
Cheers,
Clovis.

**Comment by WeiliWw** [comment]
Hi Clovis,

Thank you for the interest! To answer your questions:
- We simplified the model to be static after training. The network/coefficients are inferred by a regression model, about which you can find details in the _Method_ section of the cited paper.
- It is possible to retrain the model with extensive data. We currently cannot automate the training process, but after obtaining the new coefficients, it's relatively easy to modify this tool (mostly, just the dependent index data).

Best,
Weili

**Comment by ClovisG** [comment]
Thanks for the clarification. I still miss one point: in the methods, I see some kind of regression, whose training is not so trivial since the inferred relations K_ij is a regression on some fix values and as well depends on K_i'j' for i' and j' different from i and j respectively (in particular through the set H_b). This should involve some kind of message passing algorithm. Do you train your model with such algorithm or do you consider the set H_b to be fix during training? Or do you infer the regression coefficients iteratively, updating H_b at every iteration? If so, when do you reach convergence, and does it depend on your initialization?

Thanks for your time!
Best,
Clovis.

**Comment by WeiliWw** [comment]
Yes, we consider the set to be fixed during training. We tried to update it through iteration a few years ago, but it was not promising based on preliminary results.
